theme = "hugo-theme-learn"
canonifyURLs = true
publishDir = "docs"     # ðŸ‘ˆ ThÃªm dÃ²ng nÃ y á»Ÿ Ä‘Ã¢y

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "workshop"
  editURL = ""
  description = ""
  author = "journeyoftheaverageguy@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  ignoreLogs = ['warning-goldmark-raw-html']

[Languages]
[Languages.en]
title = "AWS Account Setup"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

[Languages.vi]
title = "Thiáº¿t láº­p AWS Account"
weight = 2
languageName = "Tiáº¿ng Viá»‡t"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20
